"""Decode Skyrim SE hkaSplineCompressedAnimation -> per-frame bone TRS JSON.

Pipeline: .hkx --(hkxc)--> XML --(this)--> anims/<name>.json
Spline decode ported from HavokLib (PredatorCZ) hka_spline_decompressor.cpp.

Usage:
    python3 hkx_anim.py <clip.hkx> ...   decode clips, then rewrite the index
    python3 hkx_anim.py --reindex        rewrite anims/index.json only

Emitted clip format (anims/<name>.json, minified):

    {
      "duration": 3.0,          # seconds
      "fps": 30.0,              # 1 / frameDuration
      "frames": 91,             # sample count; frame i is at i/fps seconds
      "bones": {
        "NPC Spine [Spn0]": {
          "pos":   [[x, y, z], ...],        # one entry per frame
          "rot":   [[x, y, z, w], ...],     # one entry per frame
          "scale": [[x, y, z], ...]         # OPTIONAL, see below
        },
        ...
      }
    }

Units/space: bone-local TRS relative to the parent bone, matching the skeleton
the HKX was authored against. Positions are Skyrim units (~1.428 cm); the
viewer applies the same scale it uses for the NIF. Rotations are unit
quaternions in xyzw order.

Rounding: positions/scales 4 decimals, quaternion components 6.

`scale` is omitted for any bone whose scale is identity (1,1,1) on every
frame, which is nearly all of them -- consumers must treat a missing `scale`
as identity. Unknown keys are ignored by the viewer, so adding tracks is
backward-compatible.

anims/index.json is a plain JSON array of clip names (file stems, no .json),
sorted; the viewer fetches it and then fetches anims/<name>.json for each.
It is regenerated by scanning anims/*.json, so it always matches what's on
disk.
"""
import json
import math
import os
import re
import struct
import subprocess
import sys
import tempfile
import xml.etree.ElementTree as ET

HKXC = os.path.expanduser('~/.cargo/bin/hkxc')


# ---------- XML extraction ----------

def load_hkx(path):
    with tempfile.TemporaryDirectory() as td:
        xml_path = os.path.join(td, 'a.xml')
        subprocess.run([HKXC, 'convert', '-i', path, '-o', xml_path, '-v', 'xml'],
                       check=True, capture_output=True)
        root = ET.parse(xml_path).getroot()
    anim = None
    for obj in root.iter('hkobject'):
        if obj.get('class') == 'hkaSplineCompressedAnimation':
            anim = obj
    assert anim is not None, 'no spline-compressed animation found'
    p = {e.get('name'): e for e in anim.findall('hkparam')}
    get = lambda n: (p[n].text or '').strip()
    info = {
        'duration': float(get('duration')),
        'num_frames': int(get('numFrames')),
        'num_tracks': int(get('numberOfTransformTracks')),
        'num_float_tracks': int(get('numberOfFloatTracks')),
        'num_blocks': int(get('numBlocks')),
        'max_frames_per_block': int(get('maxFramesPerBlock')),
        'frame_duration': float(get('frameDuration')),
        'block_offsets': [int(x) for x in (p['blockOffsets'].text or '').split()],
        'data': bytes(int(x) & 0xFF for x in (p['data'].text or '').split()),
        'track_names': [(t.text or '').strip() for t in anim.iter('hkparam')
                        if t.get('name') == 'trackName'],
    }
    return info


# ---------- quaternion dequant ----------

def read_quat40(buf, o):
    v = int.from_bytes(buf[o:o+8].ljust(8, b'\0'), 'little')
    mask = (1 << 11) - 1  # 2047
    fractal = 0.000345436
    c = [((v >> s) & 0xFFF) for s in (0, 12, 24)]
    x, y, z = ((ci - mask) * fractal for ci in c)
    shift = (v >> 36) & 3
    w_sign = -1.0 if (v >> 38) & 1 else 1.0
    w = math.sqrt(max(0.0, 1.0 - (x*x + y*y + z*z))) * w_sign
    # component order: implicit element sits at index `shift`
    out = [0.0] * 4
    src = iter([x, y, z])
    for i in range(4):
        out[i] = w if i == shift else next(src)
    return out, o + 5


def read_quat(qtype, buf, o):
    if qtype == 3:  # QT_40bit
        return read_quat40(buf, o)
    if qtype == 7:  # uncompressed
        return list(struct.unpack_from('<4f', buf, o)), o + 16
    raise NotImplementedError(f'rotation quantization {qtype}')


# ---------- spline eval (NURBS, byte knots) ----------

def find_knot_span(degree, value, n_points, knots):
    if value >= knots[n_points]:
        return n_points - 1
    low, high = degree, n_points
    mid = (low + high) // 2
    while value < knots[mid] or value >= knots[mid + 1]:
        if value < knots[mid]:
            high = mid
        else:
            low = mid
        mid = (low + high) // 2
    return mid


def bspline_weights(span, degree, frame, knots):
    n = [1.0, 0.0, 0.0, 0.0, 0.0]
    for i in range(1, degree + 1):
        for j in range(i - 1, -1, -1):
            a = (frame - knots[span - j]) / (knots[span + i - j] - knots[span - j])
            tmp = n[j] * a
            n[j + 1] += n[j] - tmp
            n[j] = tmp
    return n


class VecTrack:
    def __init__(self, axes, knots=None, degree=0):
        self.axes = axes  # 3 lists (len 1 = constant)
        self.knots = knots
        self.degree = degree

    def sample(self, frame):
        out = []
        span = None
        for vals in self.axes:
            if len(vals) == 1:
                out.append(vals[0])
                continue
            if span is None:
                span = find_knot_span(self.degree, frame, len(vals), self.knots)
                w = bspline_weights(span, self.degree, frame, self.knots)
            out.append(sum(vals[span - i] * w[i] for i in range(self.degree + 1)))
        return out


class QuatTrack:
    def __init__(self, points, knots=None, degree=0):
        self.points = points
        self.knots = knots
        self.degree = degree

    def sample(self, frame):
        if self.knots is None:
            return self.points[0]
        span = find_knot_span(self.degree, frame, len(self.points), self.knots)
        w = bspline_weights(span, self.degree, frame, self.knots)
        q = [0.0] * 4
        for i in range(self.degree + 1):
            p = self.points[span - i]
            for k in range(4):
                q[k] += p[k] * w[i]
        l = math.sqrt(sum(c*c for c in q)) or 1.0
        return [c / l for c in q]


# ---------- block decode ----------

def align(o, base, n=4):
    r = (o - base) % n
    return o if r == 0 else o + (n - r)


def decode_block(buf, base, num_tracks, num_float_tracks):
    o = base
    masks = [buf[o + i*4: o + i*4 + 4] for i in range(num_tracks)]
    o += 4 * num_tracks + num_float_tracks
    o = align(o, base)
    tracks = []

    def sub_type(mask_byte, bit):
        if mask_byte & (1 << bit):          # static (low nibble)
            return 'static'
        if mask_byte & (1 << (bit + 4)):    # spline (high nibble)
            return 'dynamic'
        return 'identity'

    for quant, pos_m, rot_m, scl_m in masks:
        pos_q = quant & 3                       # 0=8bit 1=16bit
        rot_q = ((quant >> 2) & 0xF) + 2        # +2 -> 2=32bit 3=40bit ...
        scl_q = (quant >> 6) & 3

        def read_vec(mask_byte, qtype, default):
            nonlocal o
            types = [sub_type(mask_byte, b) for b in range(3)]
            if 'dynamic' in types:
                num_items = struct.unpack_from('<H', buf, o)[0]
                degree = buf[o + 2]
                o += 3
                knots = list(buf[o:o + num_items + degree + 2])
                o += num_items + degree + 2
                o = align(o, base)
                axes, ranges = [], []
                for t in types:
                    if t == 'dynamic':
                        mn, mx = struct.unpack_from('<2f', buf, o)
                        o += 8
                        axes.append([0.0] * (num_items + 1))
                        ranges.append((mn, mx))
                    elif t == 'static':
                        axes.append([struct.unpack_from('<f', buf, o)[0]])
                        o += 4
                        ranges.append(None)
                    else:
                        axes.append([default])
                        ranges.append(None)
                for i in range(num_items + 1):
                    for a, (t, rng) in enumerate(zip(types, ranges)):
                        if t != 'dynamic':
                            continue
                        if qtype == 0:
                            v = buf[o] / 255.0
                            o += 1
                        else:
                            v = struct.unpack_from('<H', buf, o)[0] / 65535.0
                            o += 2
                        mn, mx = rng
                        axes[a][i] = mn + (mx - mn) * v
                o = align(o, base)
                return VecTrack(axes, knots, degree)
            axes = []
            for t in types:
                if t == 'static':
                    axes.append([struct.unpack_from('<f', buf, o)[0]])
                    o += 4
                else:
                    axes.append([default])
            return VecTrack(axes)

        pos = read_vec(pos_m, pos_q, 0.0)

        if rot_m & 0xF0:  # dynamic rotation
            num_items = struct.unpack_from('<H', buf, o)[0]
            degree = buf[o + 2]
            o += 3
            knots = list(buf[o:o + num_items + degree + 2])
            o += num_items + degree + 2
            if rot_q in (4, 6):
                o = align(o, base, 2)
            elif rot_q in (2, 7):
                o = align(o, base)
            points = []
            for _ in range(num_items + 1):
                q, o = read_quat(rot_q, buf, o)
                points.append(q)
            rot = QuatTrack(points, knots, degree)
        elif rot_m & 0x0F:  # static rotation
            q, o = read_quat(rot_q, buf, o)
            rot = QuatTrack([q])
        else:
            rot = QuatTrack([[0.0, 0.0, 0.0, 1.0]])
        o = align(o, base)

        scale = read_vec(scl_m, scl_q, 1.0)
        tracks.append((pos, rot, scale))
    return tracks


def decode(path):
    info = load_hkx(path)
    blocks = [decode_block(info['data'], off, info['num_tracks'],
                           info['num_float_tracks'])
              for off in info['block_offsets']]
    frames = info['num_frames']
    span = info['max_frames_per_block'] - 1  # blocks share boundary frames
    out = {'duration': info['duration'], 'fps': 1.0 / info['frame_duration'],
           'frames': frames, 'bones': {}}
    for ti, name in enumerate(info['track_names']):
        pos_frames, rot_frames, scl_frames = [], [], []
        for f in range(frames):
            b = min(f // span, len(blocks) - 1)
            local = f - b * span
            pos, rot, scale = blocks[b][ti]
            pos_frames.append([round(v, 4) for v in pos.sample(local)])
            rot_frames.append([round(v, 6) for v in rot.sample(local)])
            scl_frames.append([round(v, 4) for v in scale.sample(local)])
        track = {'pos': pos_frames, 'rot': rot_frames}
        # ponytail: drop all-identity scale tracks (nearly every bone) to keep
        # files small; consumers read a missing `scale` as (1,1,1).
        if any(s != [1.0, 1.0, 1.0] for s in scl_frames):
            track['scale'] = scl_frames
        out['bones'][name] = track
    return out


def reindex(outdir):
    """Rewrite <outdir>/index.json from the clip JSONs actually on disk."""
    names = sorted(f[:-5] for f in os.listdir(outdir)
                   if f.endswith('.json') and f != 'index.json')
    with open(os.path.join(outdir, 'index.json'), 'w') as fh:
        json.dump(names, fh)
    return names


if __name__ == '__main__':
    outdir = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'anims')
    os.makedirs(outdir, exist_ok=True)
    for path in sys.argv[1:]:
        if path == '--reindex':
            continue
        name = re.sub(r'\.hkx$', '', os.path.basename(path),
                      flags=re.IGNORECASE).lower()
        clip = decode(path)
        dst = os.path.join(outdir, name + '.json')
        with open(dst, 'w') as fh:
            json.dump(clip, fh, separators=(',', ':'))
        b = clip['bones']
        pelvis = next((n for n in b if 'Pelvis' in n), None)
        scaled = sum('scale' in t for t in b.values())
        print(f'{name}: {clip["frames"]}f {clip["duration"]}s {len(b)} tracks '
              f'({scaled} scaled) -> {dst} ({os.path.getsize(dst)//1024}KB)  '
              f'pelvis@0={b[pelvis]["pos"][0] if pelvis else "?"}')
    print('index.json:', reindex(outdir))
